# ----------- CONFIGURABLE START -----------
title:            "MiaoXinyi |Designer |GitHub blog"
description:      "生活|设计|思考"
url:              https://zhuangzhuangmiao.github.io # 域名
signoff:          "MiaoXinyi" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 12
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         设计
    url:          /design
    external:     false
  - name:         生活
    url:          /life
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
